### ISSUE TITLE
Change or conversion of units of measure

### ISSUE THREAD

**Issue by TheGreatBorg** [pinkywafer/octoprint-HA#2]
I know this is a minor thing - but still my head aches from making the calculations ;-) 

But is it by any mean possible to get the sensor.geeetech_time_remaining converted to minutes and maybe even hours ? 

![image](https://user-images.githubusercontent.com/31419036/73637239-220c5c80-4668-11ea-88b0-a0744fb95611.png)

**Comment by pinkywafer** [comment]
Using the custom button card, it is possible to play with what is displayed as it will render JavaScript for a label, so you could do: 
``` yaml
type: custom:button-card
entity: sensor.geeetech_time_remaining
show_state: false
show_label: true
label: >
  [[[
    var seconds = states['sensor.geeetech_time_remaining'].state
    var hours = parseInt(seconds / 3600)
    seconds -= (hours * 3600)
    var minutes = parseInt(seconds / 60)
    seconds -= (minutes * 60)
    return hours + " hours, " + minutes + " minutes, " + seconds + "seconds"
   ]]]
```

**Comment by TheGreatBorg** [comment]
So cool - thanks! 

So JaveScript is somehow the magic ingredient - I would hope it was easier to learn - but I can't follow the logic  

![image](https://user-images.githubusercontent.com/31419036/73644553-e4aecb80-4675-11ea-9649-59ca31cc6621.png)

**Comment by pinkywafer** [comment]
That's ok!
Essentially works like this:
`var seconds = states['......` sets a variable called seconds to the state (the seconds)
`var hours = parseInt(seconds / 3600)` sets a variable called hours to the number of hours (3600 seconds in an hour). - the parseInt is needed to give us an integer (ie 2 rather than 2.5685 for example!) 
`seconds -= (hours * 3600)` subtracts the number of hours * the number of seconds in the hour from the variable seconds
Then it's the same for the minutes, so we end up with three variables, hours, minutes and seconds
The return line then just arranges them with any text we want between. We could do:
`return hours + "h, " + minutes + "m, " + seconds + "s"` to make it more compact... whatever is between the double quotes in the return line will be what is displayed
